# Problem parameters
"Program":
    # Choose from the following initial conditions
    # 1 = Taylor Green Vortices
    # 2 = Sinusoidal Perturbation (for Channel Flows)
    # 3 = Random Perturbation (for Channel Flows)
    "Initial Condition": 1

    # Domain type indicates periodicity/non-periodicity (P/N) along X, Y and Z directions
    # If domain is periodic along X and Y, but non-periodic along Z, Domain Type = PPN
    # If periodic along all directions, Domain Type = PPP, and so on
    # For 2D runs, only X and Z direction values are considered
    "Domain Type": "PPP"

    # Dimensions of the domain
    "X Length": 1.0
    "Y Length": 1.0
    "Z Length": 1.0


# Mesh parameters
"Mesh":
    # The grid spacing along each direction can be set according to one of the following:
    # U - Uniform spacing
    # S - Single sided tangent-hyperbolic stretching (finest near one edge and coarsest at the opposite edge)
    # D - Double sided tangent-hyperbolic stretching (finest near both edges and coarsest at the center)
    # Specify the required spacing along X, Y and Z directions by using appropriate letters from above
    # Eg. Uniform spacing in X-direction, double sided tan-hyp stretching along Y and single sided tan-hyp along Z would be "UDS"
    "Mesh Type": "UUU"

    # Stretching factor to be used for tangent-hyperbolic grids - considered only when Mesh Type is TanHyp
    "X Beta": 1.0
    "Y Beta": 1.0
    "Z Beta": 1.0

    # Choose the grid sizes (for the staggered grid) as indices from the list below
    # These sizes are set to allow multigrid operations on the staggered grid
    # 2D simulations can be run by setting Y Index to 0
    # Grid sizes:   2 3 5 9 17 33 65 129 257 513 1025 2049 4097 8193 16385]
    # Size index:   0 1 2 3  4  5  6  7   8   9   10   11   12   13    14
    "X Index": 6
    "Y Index": 6
    "Z Index": 6


# Parellelization parameters
"Parallel":
    "Number of OMP threads": 1
    "X Number of Procs": 2
    "Y Number of Procs": 2


# Poisson solver parameters
"Multigrid":
    # Tolerance used in Jacobi iterations
    "Jacobi Tolerance": 1.0e-6
    # Number of restriction/prolongation steps in each V-Cycle
    "V-Cycle Depth": 3
    # Number of V-Cycles to be performed
    "V-Cycle Count": 5
    # Number of smoothing iterations to be performed before V-Cycle
    "Pre-Smoothing Count": 10
    # Number of smoothing iterations to be performed after V-Cycle
    "Post-Smoothing Count": 10
    # Array of numbers of smoothing iterations to be performed in between prolongation operations of V-Cycle at different levels *from coarsest mesh to finest mesh*
    "Inter-Smoothing Count": [10, 10, 10, 10]
